name: brillanza_app
description: "Aplicación móvil de joyería Brillanza - Proyecto Multimedia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- CORE DE BRILLANZA ---
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.1
  # Esta es la línea que faltaba para activar el login:
  google_sign_in: ^6.2.1 
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Descomenta esto cuando tengas la carpeta de imágenes lista
  # assets:
  #   - assets/images/